# Generated by Django 6.0.6 on 2026-08-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_avatar_usuario_email_verificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, default='img-avatar/default-avatar.png', upload_to='img-avatar/'),
        ),
    ]
