# Generated by Django 6.0.6 on 2026-08-17 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('events', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'borrador'), ('PUBLICADO', 'Publicado'), ('CANCELADO', 'cancelado'), ('FINALIZADO', 'finalizado')], default='BORRADOR', max_length=20),
        ),
        migrations.AddField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='eventos-img'),
        ),
        migrations.RemoveField(
            model_name='evento',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='evento',
            name='id_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.ManyToManyField(to='categorias.categoria'),
        ),
    ]
