# Generated by Django 6.0.6 on 2026-08-24 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0003_evento_estado_evento_imagen_remove_evento_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EVENTO_CANCELADO', 'Evento cancelado'), ('EVENTO_FINALIZADO', 'Evento finalizado'), ('NUEVO_EVENTO', 'Nuevo evento'), ('NUEVO_COMENTARIO', 'Nuevo comentario'), ('REPORTE', 'Reporte')], max_length=30)),
                ('mensaje', models.CharField(max_length=255)),
                ('leido', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notificaciones', to='events.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
