# Generated by Django 6.0.6 on 2026-08-28 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='comentario_adicional',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='reporte',
            name='reportado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_recibidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporte',
            name='reportador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_enviados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='motivo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
