# Generated by Django 6.0.6 on 2026-08-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_remove_reporte_comentario_adicional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
