# Generated by Django 6.0.6 on 2026-08-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_reporte_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='motivo',
            field=models.CharField(choices=[('SPAM', 'Contenido No Deseado / Spam'), ('INAPROPIADO', 'Contenido Inapropiado'), ('INCOMPLETO', 'Información Falsa o Engañosa'), ('OTRO', 'Otro motivo')], max_length=50),
        ),
    ]
