"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'                   # Configuración de carpeta de medios (archivos subidos por usuarios)
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')         # Carpeta donde se almacenarán los archivos




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-53@d##$rcl$=!-x**lf041(+r6uhkoi#$ah9ol_0dbnx9&8vsm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # local
    'users',
    'events',
    'forums',
    'categorias',
    'report',
    'notification',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Directorio global de plantillas 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # Le dice a Django que hablará con MySQL
        'NAME': 'nexus_db',                    # El nombre exacto de la base de datos en MySQL
        'USER': 'root',                        # El usuario por defecto de XAMPP
        'PASSWORD': '',                        # XAMPP por defecto viene sin contraseña (vacío)
        'HOST': '127.0.0.1',                   # Tu servidor local
        'PORT': '3306',                        # El puerto por defecto de MySQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
       
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'                  # Configurado para español de Colombia



TIME_ZONE = 'America/Bogota'             # Configurado para tu zona horaria local


USE_I18N = True

USE_TZ = True


# Custom User Model
AUTH_USER_MODEL = 'users.Usuario'        # Modelo personalizado de usuario


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/



STATIC_URL = 'static/'
STATICFILES_DIRS = [                     # Configuración de carpeta estática global
    BASE_DIR / 'static',        
]


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = [
    'https://thermos-obsessed-shortage.ngrok-free.dev',
]

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Configuración para enviar correos electrónicos a la consola durante el desarrollo
DEFAULT_FROM_EMAIL = 'noreply@nexus.com'