# Generated by Django 6.0.6 on 2026-08-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='comentarios-img/%Y/%m')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img-foros/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PUBLICADO', 'Publicado'), ('BORRADOR', 'Borrador'), ('OCULTO', 'Oculto por moderación'), ('ELIMINADO', 'Eliminado por el creador'), ('ELIMINADO_ADMIN', 'Eliminado por un administrador')], default='PUBLICADO', max_length=20)),
            ],
        ),
    ]
