# Generated by Django 6.0.6 on 2026-08-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_foroguardado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foro',
            name='estado',
            field=models.CharField(choices=[('PUBLICADO', 'Publicado'), ('OCULTO', 'Oculto por moderación'), ('ELIMINADO', 'Eliminado por el creador'), ('ELIMINADO_ADMIN', 'Eliminado por un administrador')], default='PUBLICADO', max_length=20),
        ),
    ]
